# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pruebasUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MeuWindo(object):
    def setupUi(self, MeuWindo):
        MeuWindo.setObjectName("MeuWindo")
        MeuWindo.resize(974, 724)
        self.centralwidget = QtWidgets.QWidget(MeuWindo)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 180, 321, 181))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(310, 380, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(410, 380, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(80, 80, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MeuWindo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MeuWindo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 21))
        self.menubar.setObjectName("menubar")
        MeuWindo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MeuWindo)
        self.statusbar.setObjectName("statusbar")
        MeuWindo.setStatusBar(self.statusbar)

        self.retranslateUi(MeuWindo)
        QtCore.QMetaObject.connectSlotsByName(MeuWindo)

    def retranslateUi(self, MeuWindo):
        _translate = QtCore.QCoreApplication.translate
        MeuWindo.setWindowTitle(_translate("MeuWindo", "MeuWindo"))
        self.pushButton.setText(_translate("MeuWindo", "piuPiu"))
        self.radioButton.setText(_translate("MeuWindo", "RadioButton"))
        self.radioButton_2.setText(_translate("MeuWindo", "RadioButton"))
        self.comboBox.setItemText(0, _translate("MeuWindo", "Arriba"))
        self.comboBox.setItemText(1, _translate("MeuWindo", "Abajo"))
        self.comboBox.setItemText(2, _translate("MeuWindo", "Al centro"))
        self.comboBox.setItemText(3, _translate("MeuWindo", "..."))
